### ISSUE TITLE
Accept $ref at the root of the response object

### ISSUE THREAD

**Issue by abarre** [fastify/fast-json-stringify#162]
I try to write the `response` property of a fastify route like so : 
```js
{
body: {
        name: 'user',
        description: 'Details of the new user to register',
        $ref: '/json-schema.json#/definitions/NewUserRequest',
      },
response: {
        '200': {
          description: 'OK',
          $ref: '/json-schema.json#/definitions/UserResponse',
        },
        '401': {
          description: 'Unauthorized',
          $ref: '/json-schema.json#/definitions/GenericErrorModel',
        },
        '422': {
          description: 'Unexpected error',
          $ref: '/json-schema.json#/definitions/GenericErrorModel',
        },
      },
}
```
This is actually based on a swagger definition from the real world project here : https://github.com/gothinkster/realworld/blob/master/api/swagger.json#L35...L73

After several attempt, I found a work-around by copying the definition of `UserResponse` like so :
```js
response: {
        '200': {
          type: 'object',
          description: 'OK',
          properties: {
            user: {
              $ref: '/json-schema.json#/definitions/User',
            },
          },
          required: ['user'],
        },
       //...
      },
}
```

Edit : note that the syntax is correctly supported for the validation (in the `body` and fastify-swagger)

**Comment by mcollina** [comment]
It’s not exactly clear what is the problem. Would you mind providing a failing/broken example?

**Comment by abarre** [comment]
Sorry, I did some copy/paste and didn't realize that the issue was not clearly stated.
The following syntax is not supported by `fast-json-stringify` when it's correctly supported by `ajv` or `fastify-swagger` : 
```
'200': {
          $ref: '/json-schema.json#/definitions/UserResponse',
        }
```
Since `fast-json-stringify` doesn't resolve the reference at the root level. There is multiple crashes : 
```
[1555572595350] ERROR (5407 on MBP-de-Barre): undefined unsupported
    Error: undefined unsupported
        at build (/Users/anthonybarre/github/new_app/node_modules/fast-json-stringify/index.js:107:13)
        at getValidatorForStatusCodeSchema (/Users/anthonybarre/github/new_app/node_modules/fastify/lib/validation.js:13:10)
        at /Users/anthonybarre/github/new_app/node_modules/fastify/lib/validation.js:19:21
        at Array.reduce (<anonymous>)
        at getResponseSchema (/Users/anthonybarre/github/new_app/node_modules/fastify/lib/validation.js:18:22)
        at build (/Users/anthonybarre/github/new_app/node_modules/fastify/lib/validation.js:53:31)
        at Object.afterRouteAdded (/Users/anthonybarre/github/new_app/node_modules/fastify/fastify.js:474:9)
        at after (/Users/anthonybarre/github/new_app/node_modules/fastify/fastify.js:430:25)
        at Object._encapsulateThreeParam (/Users/anthonybarre/github/new_app/node_modules/avvio/boot.js:419:7)
        at Boot.callWithCbOrNextTick (/Users/anthonybarre/github/new_app/node_modules/avvio/boot.js:341:5)
        at Boot._after (/Users/anthonybarre/github/new_app/node_modules/avvio/boot.js:232:26)
        at Plugin.exec (/Users/anthonybarre/github/new_app/node_modules/avvio/plugin.js:89:17)
        at Boot.loadPlugin (/Users/anthonybarre/github/new_app/node_modules/avvio/plugin.js:175:10)
        at release (/Users/anthonybarre/github/new_app/node_modules/fastq/queue.js:127:16)
        at Object.resume (/Users/anthonybarre/github/new_app/node_modules/fastq/queue.js:61:7)
        at Plugin.finish (/Users/anthonybarre/github/new_app/node_modules/avvio/plugin.js:166:10)
```

and if I add a `type:object`, there is no exception at the build but the serialization fails since the serializer didn't found the `properties` or `additionalProperties` key.

**Comment by mcollina** [comment]
That's definitely a bug. Would you mind adding a full example just using fast-json-stringify?

**Comment by abarre** [comment]
A minimal example is : 
```js
const fastJson = require('fast-json-stringify')
const schema = {
  title: 'Example Schema',
  $ref: 'numbers#/definitions/num'  
}

const externalSchema = {
  numbers: {
    definitions: {
      num: {
        type: 'object',
        properties: {
          int: {
            type: 'integer'
          }
        }
      }
    }
  }
}

const stringify = fastJson(schema, { schema: externalSchema })
//Error: undefined unsupported
//    at build (/fast-json-stringify/index.js:107:13)
```

**Comment by mcollina** [comment]
@Eomm would you mind taking a look?

**Comment by abarre** [comment]
Thank you for the quick fix. 
@mcollina, do you plan to release 1.15.2 soon ?

**Comment by Eomm** [comment]
@mcollina Yup, the release on GitHub has been created [v1.15.2](https://github.com/fastify/fast-json-stringify/releases/tag/1.15.2) but on npm there is not the published version (and I don't have rights to do it).

**Comment by mcollina** [comment]
done.

Il giorno mar 23 apr 2019 alle ore 04:36 Manuel Spigolon <
notifications@github.com> ha scritto:

**Comment by lazharichir** [comment]
@abarre just wondering if you are facing the same issue with the latest `fastify` version (3.4.1)? (also cc'ing @Eomm)

This is the boilerplate:
```
	instance.addSchema(
		S.object()
			.id(`#service`)
			.prop(`id`, S.string())
			.prop(`name`, S.string())
			.prop(`metadata`, S.object())
			.required([`id`, `name`])
	)

	server.post(
		`/services/`,
		{
			schema: {
				body: S.object().prop(`name`, S.string()).required(),
				response: {
					200: server.getSchema(`#service`),
					201: S.array().items(S.ref(`#service`)),
					202: { $ref: `#service` },
					203: S.ref(`#service`),
				},
			},
		},
		handler
	)
```

And:

- 200 works
- 201 works
- 202 does not work
- 203 does not work

I use `fastify-oas` for the API specs and here is the result – 202 and 203 don't work because it seems `$ref` isn't accepted at the root as per this closed issue.

<img width="1402" alt="Screenshot 2020-09-19 at 23 04 30" src="https://user-images.githubusercontent.com/12215372/93690096-7ca9da00-facc-11ea-9c9b-a039383446c6.png">
