### ISSUE TITLE
Recursion

### ISSUE THREAD

**Issue by Shiva127** [fastify/fast-json-stringify#181]
I'm trying to serialize some [recursive directory tree](https://json-schema.org/understanding-json-schema/structuring.html#recursion) without success.

And I do not find any solution, can you please help me?

## Code
``` javascript
const fastify = require('fastify')({ logger: { prettyPrint: { translateTime: true } } })

fastify.route({
  url: '/',
  method: 'GET',
  schema: {
    response: {
      200: {
        definitions: {
          directory: {
            type: 'object',
            properties: {
              name: { type: 'string' },
              subDirectories: {
                type: 'array',
                items: { $ref: '#/definitions/directory' },
                default: []
              }
            }
          }
        },
        type: 'array',
        items: { $ref: '#/definitions/directory' }
      }
    }
  },
  handler: async (request, reply) => {
    reply.send([
      { name: 'directory 1', subDirectories: [] },
      { name: 'directory 2',
        subDirectories: [
          { name: 'directory 2.1', subDirectories: [] },
          { name: 'directory 2.2', subDirectories: [] }
        ] }
    ])
  }
})

fastify.listen().catch(error => {
  fastify.log.error(error)
  process.exit(1)
})
```

## Error
```
[2019-08-12 09:54:23.895 +0000] ERROR (59647 on xxx.local): Maximum call stack size exceeded
    RangeError: Maximum call stack size exceeded
        at String.replace (<anonymous>)
        at sanitizeKey (/Users/xxx/workspace/yyy/node_modules/fast-json-stringify/index.js:520:19)
        at Object.keys.forEach (/Users/xxx/workspace/yyy/node_modules/fast-json-stringify/index.js:544:21)
        at Array.forEach (<anonymous>)
        at buildCode (/Users/xxx/workspace/yyy/node_modules/fast-json-stringify/index.js:534:40)
        at buildCodeWithAllOfs (/Users/xxx/workspace/yyy/node_modules/fast-json-stringify/index.js:644:21)
        at buildInnerObject (/Users/xxx/workspace/yyy/node_modules/fast-json-stringify/index.js:662:10)
        at buildObject (/Users/xxx/workspace/yyy/node_modules/fast-json-stringify/index.js:753:9)
        at nested (/Users/xxx/workspace/yyy/node_modules/fast-json-stringify/index.js:912:19)
        at Object.keys.forEach (/Users/xxx/workspace/yyy/node_modules/fast-json-stringify/index.js:603:20)
```

**Comment by mcollina** [comment]
Ouch! This is definitely a bug! One that’ll likely require some significant refactoring to be fixed properly.

I don’t have time right now, so a PR that addressed this would be highly welcomed.

**Comment by kalda341** [comment]
I am also having this issue.

**Comment by L2jLiga** [comment]
Let's reopen this cause issue is still there and noone fixed it yet.

**Comment by ilteoood** [comment]
Same problem here!

**Comment by kingyyy** [comment]
same here version 2.7.10
