### ISSUE TITLE
Schema with anyOf loses track of Symbols defined by the caller.

### ISSUE THREAD

**Issue by sinclairzx81** [fastify/fast-json-stringify#271]
## 🐛 Bug Report

Hi, have stumbled across an unusual error related to `anyOf` and `Symbol` properties that may exist in the schemas passed on `fastJson(schema)`. The issue only seems to relate to `anyOf`, possibly related to specific handling of `anyOf` in `fast-json-stringify` where it's somehow its loosing track of the Symbol defined by the caller. Repro below.

Related Issue: https://github.com/sinclairzx81/typebox/issues/44

### Working

The following code works fine.

```typescript
import * as fastJson from 'fast-json-stringify'

const working= fastJson({
  type: "object",
  properties: {
    value: {
      anyOf: [
        { type: "string", enum: [ "foo" ] },
        { type: "string", enum: [ "bar" ] },
        { type: "string", enum: [ "baz" ] }
      ]
    }
  },
  required: [ "value" ]
})

console.log(working({ value: 'foo' }))
```
### Not Working
The following code throws an error trying to resolve the `symbol LiteralKind`. Note that `ObjectKind` and `UnionKind` are fine, however `LiteralKind` is not, possibly related to how `anyOf` is handled in `fast-json-stringify`. 
```typescript
import * as fastJson from 'fast-json-stringify'

const ObjectKind  = Symbol('LiteralKind')
const UnionKind   = Symbol('UnionKind')
const LiteralKind = Symbol('LiteralKind')

const not_working = fastJson({
  kind: ObjectKind,
  type: "object",
  properties: {
    value: {
      kind: UnionKind,
      anyOf: [
        { kind: LiteralKind, type: "string", enum: [ "foo" ] }, // fail ?
        { kind: LiteralKind, type: "string", enum: [ "bar" ] }, // fail ?
        { kind: LiteralKind, type: "string", enum: [ "baz" ] }  // fail ?
      ]
    }
  },
  required: [ "value" ]
})

console.log(not_working({ value: 'foo' }))
```
Which results in the following AJV error originating from `fast-json-stringify`.
```bash
undefined:132
            if(ajv.validate({ kind: Symbol(LiteralKind), type: 'string', enum: [ 'foo' ] }, obj["value"]))
                                           ^

ReferenceError: LiteralKind is not defined
    at $main (eval at build (C:\Users\sinclair\Desktop\stringify\node_modules\fast-json-stringify\index.js:158:20), <anonymous>:132:44)
    at Object.<anonymous> (C:\Users\sinclair\Desktop\stringify\index.js:94:13)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```
### AJV Test
To further narrow the problem. The following code runs the same validator against the same schema using Ajv directly. This code works as expected.
```typescript
import * as Ajv from 'ajv'

const ajv         = new Ajv()
const ObjectKind  = Symbol('LiteralKind')
const UnionKind   = Symbol('UnionKind')
const LiteralKind = Symbol('LiteralKind')

const result = ajv.validate({
  kind: ObjectKind,
  type: "object",
  properties: {
    value: {
      kind: UnionKind, 
      anyOf: [
        { kind: LiteralKind, type: "string", enum: [ "foo" ] },
        { kind: LiteralKind, type: "string", enum: [ "bar" ] },
        { kind: LiteralKind, type: "string", enum: [ "baz" ] }
      ]
    }
  },
  required: [ "value" ]
}, { 
  value: 'foo'
})

console.log('is valid:', result) // true
```

## Expected behavior

Would expect `fast-json-stringify` to have the same validation behaviors as Ajv. 

## Your Environment

- *node version*: 12.18.2
- *fastify version*: 2.2.9
- Windows

**Comment by Eomm** [comment]
This seems a bug!
We should ignore the `Symbol`, would you like to send a PR to fix it?

**Comment by toddheslin** [comment]
@sinclairzx81 I've just tested this using Typebox and `fast-json-stringify` (via `fastify`) and found the following behaviour:

```js
export const CurrencyKind = Type.Union([
  Type.Literal('AED'),
  Type.Literal('AUD'),
  Type.Literal('BRL'),
  Type.Literal('CAD')
... etc
```

This now works with your PR above:
```js
const UsersBidUpdateOutput = Type.Object({
  id: Type.String(),
  currency: CurrencyKind,
  stripe_id: Type.String(),
})
```

But this one doesn't:
```js
const UserCouponsOutput = Type.Array(
  Type.Object({
    code: Type.String(),
    currency: CurrencyKind,
    amount_off: Type.String(),
    percent_off: Type.String(),
    valid: Type.Boolean(),
  })
)
```

Presumably because it's an Array of objects where one of the properties is the union of literals.

**Comment by L2jLiga** [comment]
@toddheslin I've created new issue from your comment, #279
