### ISSUE TITLE
nullable doesn't work in schemas using format and anyOf

### ISSUE THREAD

**Issue by gudleik** [fastify/fast-json-stringify#487]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.2.0

### Plugin version

5.0.6

### Node.js version

16.15.1

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.4

### Description

When schema contains both a nullable property with format, and another anyOf property, fastify-json-stringify throws this error:
`"nullable" cannot be used without "type"`.

### Steps to Reproduce

```ts
import fastJson from 'fast-json-stringify'

const json = fastJson({
  type: 'object',
  properties: {
    date: {
      format: 'date',
      type: 'string',
      nullable: true,
    },
    color: {
      anyOf: [
        {
          type: 'string',
        },
        {
          type: 'string',
        },
      ],
    },
  },
})

const result = json({date: new Date(), color: 'red'})

console.log(result) // throws '"nullable" cannot be used without "type"'```
```

Stack trace

```
/hack/node_modules/ajv/lib/compile/validate/dataType.ts:26
      throw new Error('"nullable" cannot be used without "type"')
            ^
Error: "nullable" cannot be used without "type"
    at getSchemaTypes (/hack/node_modules/ajv/lib/compile/validate/dataType.ts:26:13)
    at typeAndKeywords (/hack/node_modules/ajv/lib/compile/validate/index.ts:159:31)
    at subSchemaObjCode (/hack/node_modules/ajv/lib/compile/validate/index.ts:147:3)
    at subschemaCode (/hack/node_modules/ajv/lib/compile/validate/index.ts:124:7)
    at KeywordCxt.subschema (/hack/node_modules/ajv/lib/compile/validate/index.ts:491:5)
    at applyPropertySchema (/hack/node_modules/ajv/lib/vocabularies/applicator/properties.ts:45:11)
    at Object.code (/hack/node_modules/ajv/lib/vocabularies/applicator/properties.ts:32:9)
    at keywordCode (/hack/node_modules/ajv/lib/compile/validate/index.ts:523:9)
    at /hack/node_modules/ajv/lib/compile/validate/index.ts:265:9
    at CodeGen.code (/hack/node_modules/ajv/lib/compile/codegen/index.ts:525:33)
```

### Expected Behavior

Expected json serialization to work, and output should be `{"date":"2022-07-05","color":"red"}`.

**Comment by ivan-tymoshenko** [comment]
It will be fixed by #484. I've added the test.
