### ISSUE TITLE
array type in response schema 

### ISSUE THREAD

**Issue by kojilab** [fastify/fast-json-stringify#51]
Moving this issue https://github.com/fastify/fastify/issues/331#issuecomment-334272155 to here

Hi,

I am playing with the framework to know if I should keep using it and this crashes the server when I npm server. Not sure why and I couldn't find anything in the docs. Thanks for your insight!
```

const userSchema = {
  schema: {
    response: {
      200: {
        type: 'object',
        properties: {
          users: { type: 'array' }
        }
      }
    }
  }


TypeError: Cannot read property '$ref' of undefined
    at buildArray (/Users/om/Documents/projects/ch/node-api/node_modules/fast-json-stringify/index.js:401:19)
    at nested (/Users/m/Documents/projects/ch/node-api/node_modules/fast-json-stringify/index.js:518:19)
    at Object.keys.forEach (/Users/m/Documents/projects/ch/node-api/node_modules/fast-json-stringify/index.js:365:18)
    at Array.forEach (native)
    at buildObject (/Users/m/Documents/projects/ch/node-api/node_modules/fast-json-stringify/index.js:352:40)
    at build (/Users/m/Documents/projects/crowdhub/node-api/node_modules/fast-json-stringify/index.js:56:14)
    at getValidatorForStatusCodeSchema (/Users/m/Documents/projects/ch/node-api/node_modules/fastify/lib/validation.js:15:10)
    at /Users/m/Documents/projects/ch/node-api/node_modules/fastify/lib/validation.js:21:21
    at Array.reduce (native)
    at getResponseSchema (/Users/m/Documents/projects/ch/node-api/node_modules/fastify/lib/validation.js:20:22)
    at build (/Users/m/Documents/projects/ch/node-api/node_modules/fastify/lib/validation.js:44:28)
    at _fastify.after (/Users/m/Documents/projects/ch/node-api/node_modules/fastify/fastify.js:400:7)
    at Function._encapsulateThreeParam (/Users/m/Documents/projects/ch/node-api/node_modules/avvio/boot.js:271:7)
    at Boot.callWithCbOrNextTick (/Users/m/Documents/projects/ch/node-api/node_modules/avvio/boot.js:223:5)
    at Boot._after (/Users/m/Documents/projects/ch/node-api/node_modules/avvio/boot.js:180:26)
    at process.nextTick (/Users/m/Documents/projects/ch/node-api/node_modules/avvio/plugin.js:30:5)
```

**Comment by delvedor** [comment]
Hi!
We are expecting that you pass us an `items` property that describes the array elements.
I don't know if it is required by the json schema, but it is definitely required for us.
If you want to improve the performances of your serialization phase you should describe the shape of your payload, for example:

```js
const userSchema = {
  schema: {
    response: {
      200: {
        type: 'object',
        properties: {
          users: {
             type: 'array',
             items: {
               type: 'object',
               properties : {
                 name: { type: 'string' },
                 nickname: { type: 'string' },
                 age: { type: 'integer' }
               }
             }
          }
        }
      }
    }
  }
```

@mcollina do you think that `items` should be required?

**Comment by kojilab** [comment]
Thanks a lot!!!
