### ISSUE TITLE
array

### ISSUE THREAD

**Issue by sebdeckers** [fastify/fast-json-stringify#53]
I'm unable to set a response schema for an array in Fastify.

## Version

- `fastify@0.31.0`
- `fast-json-stringify@0.14.0`

## Error

```
/Users/seb/Code/sebdeckers/fastify/node_modules/fast-json-stringify/index.js:559
      } else throw new Error(`${schema} unsupported`)
             ^

Error: [object Object] unsupported
    at nested (/Users/seb/Code/sebdeckers/fastify/node_modules/fast-json-stringify/index.js:559:20)
    at buildArray (/Users/seb/Code/sebdeckers/fastify/node_modules/fast-json-stringify/index.js:475:14)
    at build (/Users/seb/Code/sebdeckers/fastify/node_modules/fast-json-stringify/index.js:76:14)
    at getValidatorForStatusCodeSchema (/Users/seb/Code/sebdeckers/fastify/lib/validation.js:15:10)
    at /Users/seb/Code/sebdeckers/fastify/lib/validation.js:21:21
    at Array.reduce (<anonymous>)
    at getResponseSchema (/Users/seb/Code/sebdeckers/fastify/lib/validation.js:20:22)
    at build (/Users/seb/Code/sebdeckers/fastify/lib/validation.js:47:28)
    at _fastify.after (/Users/seb/Code/sebdeckers/fastify/fastify.js:411:7)
    at Function._encapsulateThreeParam (/Users/seb/Code/sebdeckers/fastify/node_modules/avvio/boot.js:282:7)
```

## Reproducible Code

```js
const fastify = require('fastify')({logger: true})

fastify.route({
  url: '/',
  method: 'GET',
  schema: {
    response: {
      200: {
        type: 'array',
        items: {
          hello: { type: 'string' }
        }
      }
    }
  },
  handler: async (request, reply) => {
    reply.send([
      { hello: 'world' }
    ])
  }
})

fastify.listen(0, () => {
  console.log(`Listening at port ${fastify.server.address().port}`)
})
```

**Comment by allevo** [comment]
Hi!
  and thanks for checking fastify out!
I think there's a issue in your jsonschema.
[Here](
https://spacetelescope.github.io/understanding-json-schema/reference/array.html#items)
there's described how to use `items`

```
200: { type: 'array', items: { type: 'string' } }
```

Il mer 1 nov 2017, 20:53 Sebastiaan Deckers <notifications@github.com> ha
scritto:

**Comment by sebdeckers** [comment]
@allevo Thank you! 🤦🏻‍♂️ I don't know what I was thinking... seems so obvious after a good night's rest.
